//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTask
    {
        public int TaskID { get; set; }
        public Nullable<int> ID { get; set; }
        public string Title { get; set; }
        public string TaskDetail { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> Completed { get; set; }
        public Nullable<int> PriorityID { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblPriority tblPriority { get; set; }
    }
}
